### ISSUE TITLE
Documentation for data inputs

### ISSUE THREAD

**Issue by taxerap** [DragoonKiller/StateOfWarMapEditor#1]
Every time editing maps, the user has to open up the Gen 2 Map Editor to evaluate byte numbers for data like building type etc. A visual representation like Gen 3 is not desired, but it'll be better if there is a built-in references (e.g. a table or a list) for data.

**Comment by DragoonKiller** [comment]
issue is resolved due to 304eb52a295c8ab3f43afaee7fe1b77141478373
