### ISSUE TITLE
格子功能对照表

### ISSUE THREAD

**Issue by yihuang995** [DragoonKiller/StateOfWarMapEditor#3]
我测试的对照表是这样的，和readme不太一样

|按键 Button|`0`|`1`|`2`|`3`|`4`|`5`|`6`|`7`|
-|-|-|-|-|-|-|-|-
|坦克可通行 Tanks available|√||√||√||√||
|飞碟和空军可通行 Air units available|√|√|||√|√|||
|可以造炮塔 Turrets available|√||√||||||

**Comment by DragoonKiller** [comment]
25c3a6c
